---

- name: config > Directory
  file:
    path: "{{ manala_haproxy_config_file | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: manala_haproxy_config_template is not none

- name: config > Template
  template:
    src: "{{ manala_haproxy_config_template }}"
    dest: "{{ manala_haproxy_config_file }}"
    owner: root
    group: root
    mode: "0644"
  when: manala_haproxy_config_template is not none
  notify:
    - haproxy reload
